# Generated by Django 5.2.7 on 2026-07-02 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0005_remove_tradingworkflowexecution_execution_frequency_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingworkflowexecution',
            name='next_run_minutes',
            field=models.IntegerField(blank=True, help_text='Minutes until the next run, chosen by the agent and clamped to config bounds', null=True),
        ),
    ]
