# Generated by Django 5.2.7 on 2026-07-13 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tradings', '0006_tradingworkflowexecution_next_run_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingoperation',
            name='realized_pnl',
            field=models.FloatField(blank=True, help_text='Realized PnL in USDT for a close (from Binance account trades). Null for opens.', null=True),
        ),
    ]
